### ISSUE TITLE
api/dream/[id]

### ISSUE THREAD

**Issue by paullyFIRE** [RubenVerster/dream-journal-next#1]
https://github.com/RubenVerster/dream-journal-next/blob/a2199413330f0efcddcecf9fcb36d049cd017a85/pages/api/dreams/%5Bid%5D.js#L15

You're missing curly braces around `id`. This syntax is how you rename properties when destructuring, so you're actually just renaming `req.query` to a variable called `id`. Then you're trying to turn that object into a number using ==, which just doesn't work :-)

`{ query: id }` - renames query to id
`{query: { id } }` - destructures a property inside of `query` called `id`.

Secondly, highly advised against using non-strict equality, especially if we know the types of both variables. It's better to be clearer in our syntax about what types we're working with, for ourselves and the next developer.

Consider something like: `const filtered = dreams.filter((dream) => dream.id == Number(id))`

This will become more obvious and relevant when you start working with typescript and the compiler forces stricter rules 👍

**Comment by RubenVerster** [comment]
I'll try it out on my side and commit the changes if it works! Thank you
for the input. Much appreciated :D
Kind regards,
Ruben Verster

Nothing to it, except working smart and working hard
Fill your day with prosperity!
